<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<TargetFrameworks>net7.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SeekingYHWH.Scriptures</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
    <ProjectReference Include="..\SeekingYHWH.Scriptures.Querys\SeekingYHWH.Scriptures.Querys.csproj" />
    <ProjectReference Include="..\SeekingYHWH.Scriptures.Search\SeekingYHWH.Scriptures.Search.csproj" />
  </ItemGroup>

</Project>
