<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SeekingYHWH.Scriptures</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SeekingYHWH.Scriptures.ConvertPassages\SeekingYHWH.Scriptures.ConvertPassages.csproj" />
	</ItemGroup>

</Project>
