<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
		<RootNamespace>SeekingYHWH.Scriptures</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SeekingYHWH.Scriptures.Querys.Parsers\SeekingYHWH.Scriptures.Querys.Parsers.csproj" />
	  <ProjectReference Include="..\SeekingYHWH.Scriptures.Querys\SeekingYHWH.Scriptures.Querys.csproj" />
	</ItemGroup>

</Project>
